package e

// Proxy
const (
	CACHE_USER_TOKEN     = "CACHE_USER_TOKEN"
	CACHE_IP             = "IP"
	CACHE_PROXY_IP       = "CACHE_PROXY_IP"
	CACHE_PROXY_MACHINE  = "CACHE_PROXY_MACHINE"
	CACHE_PROXY_SUPPLIER = "CACHE_SUPPLIER"

	CACHE_USER_TOKEN_REQ_BYTES  = "CACHE_USER_TOKEN_REQ_BYTES"
	CACHE_USER_TOKEN_RESP_BYTES = "CACHE_USER_TOKEN_RESP_BYTES"

	CACHE_BYPASS_PROXY_SUPPLIER = "CACHE_BYPASS_PROXY_SUPPLIER"
	CACHE_BYPASS                = "BYPASS"
)
