package e

// Proxy
const (
	CACHE_USER           = "CACHE_USER"
	CACHE_USER_TOKEN     = "CACHE_USER_TOKEN"
	CACHE_IP             = "IP"
	CACHE_PROXY_IP       = "CACHE_PROXY_IP"
	CACHE_PROXY_MACHINE  = "CACHE_PROXY_MACHINE"
	CACHE_PROXY_SUPPLIER = "CACHE_SUPPLIER"

	CACHE_USER_TOKEN_REQ_BYTES  = "CACHE_USER_TOKEN_REQ_BYTES"
	CACHE_USER_TOKEN_RESP_BYTES = "CACHE_USER_TOKEN_RESP_BYTES"

	CACHE_BYPASS_PROXY_SUPPLIER = "CACHE_BYPASS_PROXY_SUPPLIER"
	CACHE_BYPASS                = "BYPASS"
)

// Summary
const (
	CACHE_LUMINATI_DATACENTER_USAGE_REQ  = "CACHE_LUMINATI_DATACENTER_USAGE_REQ"
	CACHE_LUMINATI_DATACENTER_USAGE_RESP = "CACHE_LUMINATI_DATACENTER_USAGE_RESP"

	CACHE_LUMINATI_RESIDENTIAL_USAGE_REQ  = "CACHE_LUMINATI_RESIDENTIAL_USAGE_REQ"
	CACHE_LUMINATI_RESIDENTIAL_USAGE_RESP = "CACHE_LUMINATI_RESIDENTIAL_USAGE_RESP"
	CACHE_LUMINATI_ISP_USAGE_REQ          = "CACHE_LUMINATI_ISP_USAGE_REQ"
	CACHE_LUMINATI_ISP_USAGE_RESP         = "CACHE_LUMINATI_ISP_USAGE_RESP"

	CACHE_OXYLAB_RESIDENTIAL_USAGE_REQ  = "CACHE_OXYLAB_RESIDENTIAL_USAGE_REQ"
	CACHE_OXYLAB_RESIDENTIAL_USAGE_RESP = "CACHE_OXYLAB_RESIDENTIAL_USAGE_RESP"

	CACHE_922_RESIDENTIAL_USAGE_REQ  = "CACHE_922_RESIDENTIAL_USAGE_REQ"
	CACHE_922_RESIDENTIAL_USAGE_RESP = "CACHE_922_RESIDENTIAL_USAGE_RESP"

	CACHE_IPROYAL_ISP_USAGE_REQ  = "CACHE_IPROYAL_ISP_USAGE_REQ"
	CACHE_IPROYAL_ISP_USAGE_RESP = "CACHE_IPROYAL_ISP_USAGE_RESP"

	CACHE_INSTANTPROXIES_USAGE_REQ  = "CACHE_INSTANTPROXIES_USAGE_REQ"
	CACHE_INSTANTPROXIES_USAGE_RESP = "CACHE_INSTANTPROXIES_USAGE_RESP"
)
