package e

// Proxy
const (
	CACHE_USER_TOKEN     = "CACHE_USER_TOKEN"
	CACHE_IP             = "IP"
	CACHE_PROXY_IP       = "CACHE_PROXY_IP"
	CACHE_PROXY_MACHINE  = "CACHE_PROXY_MACHINE"
	CACHE_PROXY_SUPPLIER = "CACHE_SUPPLIER"
)
